baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Liam Fox'
theme = "hugo-bearcub"
enableRobotsTXT = true

[menu]

  [[menu.main]]
  name = "About"
  url = "/"
  weight = 1

[params]
  description = "Researcher in Geography"
  footer = "© 2025 Liam Fox"
  enableDarkMode = true
  madeWith = "Built with Hugo"

[params.author]
  name = "Liam Fox"
  email = "your-email@example.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


